### ISSUE TITLE
Change default port

### ISSUE THREAD

**Issue by danjee** [decebals/pippo#132]
Wanting to change the default port for the sample application with the code

```java
public static void main(String[] args) {
        Pippo pippo = new Pippo();
        WebServerSettings settings = new WebServerSettings().port(8080);
        JettyServer server = new JettyServer();
        server.setSettings(settings);
        pippo.setServer(server);
        pippo.getApplication().GET("/", new RouteHandler() {

            @Override
            public void handle(RouteContext routeContext) {
                routeContext.send("Hello World!");
            }
        });
        pippo.start();
    }
```
led me to the error:

```java
Exception in thread "main" java.lang.NullPointerException
	at ro.pippo.jetty.JettyServer.createPippoHandler(JettyServer.java:108)
	at ro.pippo.jetty.JettyServer.start(JettyServer.java:63)
	at ro.pippo.core.Pippo.start(Pippo.java:81)
	at ro.test.pippo.App.main(App.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by gitblit** [comment]
How about this instead:

```java
Pippo pippo = new Pippo();
pippo.getServer().getSettings().port(8080);
pippo.getApplication().GET("/", new RouteHandler() {
    @Override
    public void handle(RouteContext routeContext) {
        routeContext.send("Hello World!");
    }
});
pippo.start();
```

**Comment by decebals** [comment]
In [manual](http://www.pippo.ro/doc/server.html) we have two approach: `pippo.getServer().getSettings().port(8081)` or `server.port = 8081` in _application.properties_. 
I will take a look in code to prevent this situation with NPE.

**Comment by danjee** [comment]
Hello, the line
```java
pippo.getServer().getSettings().port(8080);
```
changed the port. I was surprised of the NPE.
Thanks
