### ISSUE TITLE
Json output

### ISSUE THREAD

**Issue by danjee** [decebals/pippo#133]
I've tested a JSON sample like this with the 0.4.2 release:

```java
public class PippoController extends Application{
    @Override
    protected void onInit() {
        GET("/shop", new RouteHandler() {
            public void handle(RouteContext routeContext) {
                Shop shop = createShop();
                routeContext.json().send(shop);
            }
        });
    }

    private Shop createShop(){
        Shop shop = new Shop();
        shop.setName("KFC");
        shop.setStaff(new String[]{"messi","ronaldo"});
        return shop;
    }
}
```

The output was:
```shell
curl localhost:8338/shop
<html><body><div>Cannot find a route for 'GET /shop'</div><div>Available routes:</div><ul style=" list-style-type: none; margin: 0; "><li>GET /shop</li></ul></b
```

And the error was:

```java
ro.pippo.core.PippoRuntimeException: You must set a content type engine for 'application/json; charset=UTF-8'
	at ro.pippo.core.Response.send(Response.java:818)
	at ro.pippo.core.Response.send(Response.java:809)
	at ro.pippo.core.route.DefaultRouteContext.send(DefaultRouteContext.java:223)
	at ro.test.pippo.PippoController$1.handle(PippoController.java:17)
	at ro.pippo.core.route.DefaultRouteContext.handleRoute(DefaultRouteContext.java:339)
	at ro.pippo.core.route.DefaultRouteContext.next(DefaultRouteContext.java:249)
```

**Comment by danjee** [comment]
XML is working well. I will add the Shop class as well

```java
@XmlRootElement
public class Shop {
    private String name;
    private String staff[];

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String[] getStaff() {
        return staff;
    }

    public void setStaff(String[] staff) {
        this.staff = staff;
    }
}
```

**Comment by gitblit** [comment]
You need to add one of the Pippo JSON engines to your classpath.  Add a dependency on either `pippo-gson` or `pippo-fastjson`.  `pippo-jackson` is coming in the next release.

**Comment by danjee** [comment]
Great,
Now it works, but I think a clearer error will be more appropriate
Thanks

**Comment by danjee** [comment]
The error is clear enough.
