### ISSUE TITLE
Recursion in error handler when provoking a 404 with Pebble

### ISSUE THREAD

**Issue by rygel** [decebals/pippo#163]
Hello,

I am trying to setup a test project using the maven quickstart archtype (0.5.0). It works perfect with the default settings. When I try to access a URL which is not defined (/login) I get a nicely rendered 404.
However, when I switch the Template Engine from Freemarker to Pebble, I get the following exception:
```
00:32:31 [qtp1486371051-18] DEBUG ro.pippo.core.route.RouteDispatcher - Returned status code 404 for GET '/login'
00:32:31 [qtp1486371051-18] WARN org.eclipse.jetty.servlet.ServletHandler - /login
ro.pippo.core.PippoRuntimeException: Recursion in error handler
	at ro.pippo.core.DefaultErrorHandler.checkForRecursion(DefaultErrorHandler.java:311)
	at ro.pippo.core.DefaultErrorHandler.handle(DefaultErrorHandler.java:171)
	at ro.pippo.core.route.RouteDispatcher.onRouteDispatch(RouteDispatcher.java:164)
	at ro.pippo.core.route.RouteDispatcher.dispatch(RouteDispatcher.java:99)
	at ro.pippo.core.PippoFilter.doFilter(PippoFilter.java:139)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at ro.pippo.jetty.JettyServer$PippoHandler.doHandle(JettyServer.java:148)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by decebals** [comment]
I see that it's a WARN but the stacktrace is disturbing. Can you add more information (maybe some code snippet)?
Maybe @gitblit can help you more.

**Comment by rygel** [comment]
I have done some more debugging and think I found the reason:
The `PippoTemplateLoader` cannot find the template for the error. In this case the file `pippo/404notFound`. When the `PippoTemplateLoader` constructs the path & filename of the template to load it adds a separator char.
```java
if (!getPrefix().endsWith(String.valueOf(File.separatorChar))) {
                path.append(File.separatorChar);
            }
```
And as I am using Windows it adds a backslash (`templates\pippo/404notFound.peb`). Later the `ClasspathUtils` are not able to find the file, because the single backslash needs to be escaped by a second one. I quickly tested my theory by just hard-coding the use of a slash in the `path.append`.
```java
if (!getPrefix().endsWith(String.valueOf(File.separatorChar))) {
                //path.append(File.separatorChar);
                path.append('/');
            }
```
With this change the template is found and I get the nicely rendered error message :)

However, I am not sure how to fix this permanently. Is it ok to always use the slash? So because it is loaded from the classpath no difference between Windows and Linux/MacOS is made?

**Comment by gitblit** [comment]
The stacktrace is good - means it's working.  :)

As you've found it's possible to cause a stackoverflow within the ErrorHandler due to the TemplateEngine.  In your case an app error triggered the ErrorHandler to render the exception - but that rendering caused a nested error which triggered the ErrorHandler to render the nested exception which..... so forth and so on.   That is what checkForRecursion blocks: stackoverflow on handling an error.

Your analysis sounds right to me.

It's always safe to use forward-slashes for the filesystem and this approach generally works best.  Not sure how that `File.separatorChar` crept in there.  I think it's safe to replace both instances of `File.separatorChar`.

**Comment by rygel** [comment]
Thank you for your answer. I now understand the logic for the ErrorHandler better :)

Should I create a pull request?

**Comment by gitblit** [comment]
Sure.  Let's also take a survey of the other engines to see if that same behavior crept into all of them.

**Comment by rygel** [comment]
I have also checked the other template engines. They did not have the same behavior.

**Comment by decebals** [comment]
Is it ok now? If yes, please close it.

**Comment by rygel** [comment]
The Pebble Template Engine was the only one affected.
