### ISSUE TITLE
Exception handling for requests with arrays and very large numbers

### ISSUE THREAD

**Issue by lmicra** [decebals/pippo#209]
Hello,

I'm getting the following exception with requests like:

//pippo-server/?t[14234234722234234234234123]

```
ERROR: UT005023: Exception handling request to /
java.lang.NumberFormatException: For input string: "14234234722234234234234123"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:583)
        at java.lang.Integer.parseInt(Integer.java:615)
        at ro.pippo.core.Request.initParameters(Request.java:148)
        at ro.pippo.core.Request.<init>(Request.java:74)
        at ro.pippo.core.RequestResponseFactory.createRequest(RequestResponseFactory.java:36)
        at ro.pippo.core.PippoFilter.doFilter(PippoFilter.java:117)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
        at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by gitblit** [comment]
Right.  The array support assumes 32-bit int indexes, not 64-bit longs.  Are you experimenting or do you have a real need for long indexes?  A little further into that method the array is instantiated of the size *maxIndex+1*.  When using long indexes it's not that crazy to consider that Pippo could throw out-of-memory errors in some situations.

**Comment by lmicra** [comment]
I was configuring a facebook tab, and facebook app sends this kind of request. I've notice the framework uses Integers ( https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/Request.java#L139 ) the problem here is that it just breaks, it won't flow to the request handler. It would be better to implement a try catch for cases where the parameters cannot be succesfully parsed.

**Comment by decebals** [comment]
The problem is that pippo "feels" that your parameter is a indexed parameter arrays e.g. setting[0], setting[1], setting[2] and sure it's not in your case.
