### ISSUE TITLE
pipo-jetty problem in version 0.7.0 and higher

### ISSUE THREAD

**Issue by barrantesgerman** [decebals/pippo#236]
When I built with the Maven archetype
```
mvn archetype:generate \
  -DarchetypeGroupId=ro.pippo \
  -DarchetypeArtifactId=pippo-quickstart \
  -DarchetypeVersion=0.7.0
```

And Run:

```
mvn compile exec:java
```

I get

```
11:10:58 [main] DEBUG ro.pippo.core.Pippo - Application 'PippoApp v1.0.0'
11:10:58 [main] DEBUG ro.pippo.core.util.ServiceLocator - Locate service 'ro.pippo.core.WebServer' using ServiceLoader
Exception in thread "main" java.util.ServiceConfigurationError: ro.pippo.core.WebServer: Provider ro.pippo.jetty.JettyServer could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:224)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:181)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:377)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
	at ro.pippo.core.util.ServiceLocator.locateAll(ServiceLocator.java:45)
	at ro.pippo.core.util.ServiceLocator.locate(ServiceLocator.java:36)
	at ro.pippo.core.Pippo.getServer(Pippo.java:59)
	at ro.pippo.core.Pippo.start(Pippo.java:74)
	at com.hbv.PippoLauncher.main(PippoLauncher.java:12)
Caused by: java.lang.UnsupportedClassVersionError: org/eclipse/jetty/server/Connector : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2585)
	at java.lang.Class.getConstructor0(Class.java:2885)
	at java.lang.Class.newInstance(Class.java:350)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:373)
	... 6 more
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
```

I changed in the pom pipo-jetty by pippo-undertow and it work fine

**Comment by barrantesgerman** [comment]
Sorry, it was my mistake, I was using JRE JRE 7 instead of 8
I saw this later
http://stackoverflow.com/questions/10382929/how-to-fix-unsupported-major-minor-version-51-0-error
