### ISSUE TITLE
Errors Configuring Underlying Tomcat Server to use HTTPS without Client Auth

### ISSUE THREAD

**Issue by JPercivall** [decebals/pippo#262]
The problem arises when the keystore is properly set (location, password and alias) but no truststore is set. I get a file not found exception because it's looking for a file with name "null" (stack trace at end). 

Also of note, Tomcat isn't currently using the truststore because TomcatServer.java isn't set to use ClientAuth[1]. It would be nice to have this exposed as a TomcatSettings Property.

[1] https://github.com/decebals/pippo/blob/93f71655481f3133310019317d90467485f37e1f/pippo-tomcat/src/main/java/ro/pippo/tomcat/TomcatServer.java#L113-L113

SEVERE: Failed to load keystore type JKS with path null due to /Users/jpercivall/projects/edge/nifi-minifi/minifi-nar-bundles/minifi-framework-bundle/minifi-framework/minifi-runtime/target/tomcat_home/null (No such file or directory)
java.io.FileNotFoundException: /Users/jpercivall/projects/edge/nifi-minifi/minifi-nar-bundles/minifi-framework-bundle/minifi-framework/minifi-runtime/target/tomcat_home/null (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.tomcat.util.file.ConfigFileLoader.getInputStream(ConfigFileLoader.java:74)
	at org.apache.tomcat.util.net.jsse.JSSESocketFactory.getStore(JSSESocketFactory.java:444)
	at org.apache.tomcat.util.net.jsse.JSSESocketFactory.getTrustStore(JSSESocketFactory.java:407)
	at org.apache.tomcat.util.net.jsse.JSSESocketFactory.getTrustManagers(JSSESocketFactory.java:658)
	at org.apache.tomcat.util.net.jsse.JSSESocketFactory.getTrustManagers(JSSESocketFactory.java:570)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:360)
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:742)
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:457)
	at org.apache.coyote.http11.AbstractHttp11JsseProtocol.init(AbstractHttp11JsseProtocol.java:120)
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:960)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:567)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:851)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:139)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:337)
	at ro.pippo.tomcat.TomcatServer.start(TomcatServer.java:86)
	at ro.pippo.core.Pippo.start(Pippo.java:76)
	at org.apache.nifi.minifi.configuration.RestChangeListener$RunServer.run(RestChangeListener.java:172)
	at java.lang.Thread.run(Thread.java:745)

**Comment by decebals** [comment]
Now the "clientAuth" attribute is configurable. Also I released a new SNAPSHOT version. 
Please tell me if you need other modifications.

**Comment by JPercivall** [comment]
Awesome, I may just be missing it but does this address the other part of the issue that not passing in a truststore currently leads to errors?

**Comment by decebals** [comment]
I don't use Tomcat in my projects so I am not a Tomcat expert. Maybe @danjee can help us.

**Comment by JPercivall** [comment]
My guess would be that you only set them when client auth is used, like so:

```
if (getSettings().getClientAuth()){
          connector.setAttribute("truststoreFile", getSettings().getTruststoreFile());
          connector.setAttribute("truststorePass", getSettings().getTruststorePassword());
}
```

**Comment by decebals** [comment]
I cannot test your code. Please fork Pippo, make modifications and test these modifications on your computer. If everything is OK please submit a PR or tell us what is wrong in the actual code.

**Comment by danjee** [comment]
I will have a look at it. If your stores are self signed would you please share them with us. Thank you

**Comment by decebals** [comment]
@JPercivall If the issue is resolved please close it.

**Comment by JPercivall** [comment]
Closing - Thanks @decebals

**Comment by decebals** [comment]
You are welcome! 
I updated the SNAPSHOT version to contain this fix.
