### ISSUE TITLE
Working with pippo test

### ISSUE THREAD

**Issue by munendrasn** [decebals/pippo#308]
Hi,
I am new user of Pippo.

Using `pippo-test` for writing test cases
I referred `pippo.ro` couldn't find any documentation for pippo tests.

Below is the snippet.
```java
public class ServiceApplicationTest {

   // pippo app test instance with random port
    @ClassRule
    public  static PippoRule pippoRule = new PippoRule(new ServiceApplication(), AvailablePortFinder.findAvailablePort());

    @Test
    public void testServiceApplication() {
        PippoTest.get("/error");
    }

}
```

Running tests gives me this.
I am unable to figure it out the reason. Need some help
```java
java.lang.NullPointerException
	at ro.pippo.core.WebServerSettings.<init>(WebServerSettings.java:38)
	at ro.pippo.jetty.JettySettings.<init>(JettySettings.java:39)
	at ro.pippo.jetty.JettyServer.createDefaultSettings(JettyServer.java:83)
	at ro.pippo.jetty.JettyServer.createDefaultSettings(JettyServer.java:49)
	at ro.pippo.core.AbstractWebServer.getSettings(AbstractWebServer.java:34)
	at ro.pippo.test.PippoRule.createPippo(PippoRule.java:59)
	at ro.pippo.test.PippoRule$2.evaluate(PippoRule.java:104)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by decebals** [comment]
I feel that it's a bug introduced by https://github.com/decebals/pippo/commit/7afec711526f4a0bbeb4dee000e48f08f87ce66f.
I will try to fix it.

**Comment by decebals** [comment]
Sorry for delay. 
If everything is OK I can release a new version (9.0.1). I updated the SNAPSHOT version.

**Comment by munendrasn** [comment]
Thank you
I will run tests with updated snapshot.
Will notify you about the results.

**Comment by munendrasn** [comment]
Im getting Dependency not found Error while using the snapshot

**Comment by decebals** [comment]
> Im getting Dependency not found Error while using the snapshot

Can you give me more info (a stacktrace or something else)?

**Comment by munendrasn** [comment]
Added this.
```
<repositories>
    <repository>
        <id>sonatype-nexus-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```
```
        <dependency>
            <groupId>ro.pippo</groupId>
            <artifactId>pippo-test</artifactId>
            <version>0.9.0-SNAPSHOT</version>
        </dependency>
```
Also, at https://oss.sonatype.org/content/repositories/snapshots/ro/pippo/pippo-test/
Only `0.10.0-SNAPSHOT` available

**Comment by decebals** [comment]
See in the documentation [Maven](http://www.pippo.ro/dev/maven.html) section.
The correct SNAPSHOT version is `0.10.0-SNAPSHOT`.

**Comment by munendrasn** [comment]
Oh..my bad
Apologies and Thank you :)

**Comment by munendrasn** [comment]
Used the `0.10.0-SNAPSHOT` it works fine.

**Comment by decebals** [comment]
By the way, it's an old [issue](https://github.com/decebals/pippo-site/issues/23) created by me on pippo-site project (documentation) related to lack of documentation for pippo-test. If I have a little time today I will add a new section (Testing) about this subject.
Also, another (custom) approach for testing Pippo routes is to use OkHttp as Http client. If you are interested by this approach you can take a look at [BenchmarkTests](https://github.com/robertoestivill/FrameworkBenchmarks/blob/52ba4059e32397eee8ca81d1fa1f65cc64bcb8a9/frameworks/Java/pippo/src/test/java/ro/pippo/benchmark/BenchmarkTests.java) class written by @robertoestivill.

**Comment by munendrasn** [comment]
Sure, i will look into it.
Thanks again for your prompt reply

**Comment by munendrasn** [comment]
@decebals ,
with `0.10.0-SNAPSHOT` while starting main pippo server,
```
Exception in thread "main" java.lang.NullPointerException
	at ro.pippo.core.Pippo.start(Pippo.java:88)
	at com.unbxd.feed.service.ServiceMain.main(ServiceMain.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
2016-09-07 16:03:16,753 — WARN ro.pippo.core.Pippo(stop):94 — Server is not started
```

But with `0.9.0` it works fine. but get previous error while running tests

**Comment by decebals** [comment]
Fixed. Please [build](http://www.pippo.ro/dev/how-to-build.html) Pippo on your machine and tell me if the modification solves the problem. Thanks!

**Comment by munendrasn** [comment]
Build failed
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test)
```

**Comment by decebals** [comment]
Something is wrong with your environment but I don't have time to see where is the problem. I published a new SNAPSHOT.

**Comment by decebals** [comment]
Added a new section [Testing](http://www.pippo.ro/doc/testing.html) in documentation.

**Comment by munendrasn** [comment]
@decebals, able to build pippo.
Also, tests are successfully run using `0.10.0-SNAPSHOT`
