### ISSUE TITLE
Pippo 0.9.0 Undertow NullPointerException when changing webserver settings

### ISSUE THREAD

**Issue by SergiX44** [decebals/pippo#312]
As a title, after upgrade to 0.9.0, the application crash with a nullpointerexception using undertow webserver:

This is a part of code:
```
MyApp panel = new MyApp();
Pippo pippo = new Pippo(panel);

pippo.getServer().getSettings().host(server_host); <-- This throw the nullpointer
pippo.getServer().getSettings().port(server_port); <-- (and this)

pippo.start();
```

The stacktrace:
```
Exception in thread "main" java.lang.NullPointerException
	at ro.pippo.core.WebServerSettings.<init>(WebServerSettings.java:38)
	at ro.pippo.undertow.UndertowSettings.<init>(UndertowSettings.java:39)
	at ro.pippo.undertow.UndertowServer.createDefaultSettings(UndertowServer.java:107)
	at ro.pippo.undertow.UndertowServer.createDefaultSettings(UndertowServer.java:62)
	at ro.pippo.core.AbstractWebServer.getSettings(AbstractWebServer.java:34)
	at it.myapp.MyApplication.<init>(MyApplication.java:86)
	at it.myapp.MyApplication.main(MyApplication.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

If i rollback the pom to 0.8.0, it work correctly.

**Comment by anantheshadiga** [comment]
This issue has been already mentioned in #308 , You need to use 0.10.0-SNAPSHOT which will solve your issue.

**Comment by decebals** [comment]
It's a critical issue. Today I will release a new version (9.0.1) that contains the fix. Thanks @anantheshadiga for your comment.

**Comment by SergiX44** [comment]
Fixed with last release, thanks!
