### ISSUE TITLE
QuickStart install error

### ISSUE THREAD

**Issue by AugustoEMoreira** [decebals/pippo#362]
When i run the command "mvn install", the below error is shown
i'm definitely not an maven user, so i'm a little bit lost
Thanks

```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for ro.pippo:pippo-quickstart:[unknown-version]: Could not find artifact ro.pippo:pippo-parent:pom:1.4.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for ro.pippo:pippo-quickstart:[unknown-version]: Could not find artifact ro.pippo:pippo-parent:pom:1.4.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13

        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:382)
        at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:400)
        at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:391)
        at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:78)
        at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:511)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:221)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR]   The project ro.pippo:pippo-quickstart:[unknown-version] (C:\Users\vitor\Documents\Qargo\pippoBackEnd\quickstart\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for ro.pippo:pippo-quickstart:[unknown-version]: Could not find artifact ro.pippo:pippo-parent:pom:1.4.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact ro.pippo:pippo-parent:pom:1.4.0-SNAPSHOT
        at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:197)
        at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:243)
        at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1051)
        at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:829)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:331)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:429)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:398)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:361)
        at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:400)
        at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:391)
        at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:78)
        at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:511)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:221)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact ro.pippo:pippo-parent:pom:1.4.0-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:453)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:255)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:232)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:303)
        at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:193)
        ... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact ro.pippo:pippo-parent:pom:1.4.0-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:443)
        ... 29 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by decebals** [comment]
> Could not find artifact ro.pippo:pippo-parent:pom:1.4.0-SNAPSHOT

It is a good reason to use the SNAPSHOT version  instead of the last release  version (1.3.0) ?

**Comment by AugustoEMoreira** [comment]
No, i'm just following the quickstart tutorial.
i changed the pom file to 1.3.0 and worked, thanks

**Comment by decebals** [comment]
:+1: If you encounter any problem please use the [forum](https://groups.google.com/forum/#!forum/pippo-java).
