### ISSUE TITLE
Request hangs on GET with content length header

### ISSUE THREAD

**Issue by munendrasn** [decebals/pippo#373]
Whenever `content-length` is specified in request GET, request get blocked. 
https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/Request.java#L405 - to get body. 
Call gets blocked at this line - https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/Request.java#L405

on `reader.read(buffer)` - becoming blocking on IO calls.
I was using undertow server and changed to jetty server to know if it is server issue. 

I thought that since body is not allowed in GET, we return empty string whenever it is GET and you call `getBody()`
but i tried for other methods also, whenever `content-length` is set and body is not specified then request becomes blocking
Observed this behavior in 1.2+ pippo

**Comment by decebals** [comment]
A quick start demo (or a code snippet) is welcome. I am curios to see the nature of this problem. Recently (see https://github.com/decebals/pippo/commits/master) I upgraded Jetty and Undertow to the last version. If you have some time please check with SNAPSHOT version.

**Comment by munendrasn** [comment]
I even tested with tomcat, it is throwing exception after 1minute because of socketTimeout
with stack trace
```
2017-07-12 21:28:21,646 ERROR r.p.c.DefaultErrorHandler [http-nio-6969-exec-1] ro.pippo.core.DefaultErrorHandler.handle(DefaultErrorHandler.java:181) Exception when reading the request body ro.pippo.core.PippoRuntimeException: Exception when reading the request body
	at ro.pippo.core.Request.getBody(Request.java:405)
	at com.unbxd.brewer.request.Request.get(Request.java:100)
	at com.unbxd.brewer.SearchApplication.getResponse(SearchApplication.java:137)
	at com.unbxd.brewer.SearchApplication.lambda$onInit$1(SearchApplication.java:84)
	at ro.pippo.core.route.DefaultRouteContext.handleRoute(DefaultRouteContext.java:394)
	at ro.pippo.core.route.DefaultRouteContext.next(DefaultRouteContext.java:276)
	at ro.pippo.core.route.RouteDispatcher.onRouteDispatch(RouteDispatcher.java:153)
	at ro.pippo.core.route.RouteDispatcher.dispatch(RouteDispatcher.java:101)
	at ro.pippo.core.PippoServlet.service(PippoServlet.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException
	at org.apache.tomcat.util.net.NioBlockingSelector.read(NioBlockingSelector.java:202)
	at org.apache.tomcat.util.net.NioSelectorPool.read(NioSelectorPool.java:250)
	at org.apache.tomcat.util.net.NioSelectorPool.read(NioSelectorPool.java:231)
	at org.apache.coyote.http11.InternalNioInputBuffer.fill(InternalNioInputBuffer.java:133)
	at org.apache.coyote.http11.InternalNioInputBuffer$SocketInputBuffer.doRead(InternalNioInputBuffer.java:177)
	at org.apache.coyote.http11.filters.IdentityInputFilter.doRead(IdentityInputFilter.java:110)
	at org.apache.coyote.http11.AbstractInputBuffer.doRead(AbstractInputBuffer.java:414)
	at org.apache.coyote.Request.doRead(Request.java:476)
	at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:350)
	at org.apache.tomcat.util.buf.ByteChunk.substract(ByteChunk.java:395)
	at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:375)
	at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:190)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.Reader.read(Reader.java:140)
	at ro.pippo.core.util.IoUtils.copy(IoUtils.java:69)
	at ro.pippo.core.util.IoUtils.copy(IoUtils.java:78)
	at ro.pippo.core.util.IoUtils.toString(IoUtils.java:60)
	at ro.pippo.core.Request.getBody(Request.java:403)
	... 25 more
```
In case of jetty and undertow it just hangs
this problem can be demonstrated using pippo-demo app..make a request with content-length set and try to getBody using `request.getBody()`

**Comment by decebals** [comment]
Application class:
```java
// #373
GET("/373", routeContext -> {
    Request request = routeContext.getRequest();
    String body = request.getBody();
    System.out.println("body = " + body);
    routeContext.send(body);
});
```

Test class:
```java
public class Issue373 extends PippoTest {

    @Rule
    public PippoRule pippoRule = new PippoRule(new PippoApplication());

    @Test
    public void test1() {
        given()
            .header(Header.CONTENT_LENGTH, 200)
        .when()
            .get("/373")
            .then()
            .statusCode(StatusCode.OK);
    }

}
```

Is it OK how I test?

**Comment by munendrasn** [comment]
Yeah..does the get request work??

**Comment by decebals** [comment]
I have an error `org.apache.http.ProtocolException: Content-Length header already present`.

**Comment by munendrasn** [comment]
okay..I haven't tested by writing test case. did you run application and make a request using from `curl` or postman?? does that also work?? I tested on pippo 1.4, request goes to blocking

**Comment by decebals** [comment]
I cannot run via PippoTest, probably is a bug in RestAssured (I updated RestAssured to 2.9.0 from 2.2.0 and the error persist). 
I use `Advanced REST client` plugin from Chrome and I can replicate your problem. What is strange is a run OK in few iterations. I will try also to send the request via curl.
My error stack trace with error is (Jetty):
```
20:29:18 [qtp943842763-15] ERROR ro.pippo.core.DefaultErrorHandler - Exception when reading the request body
ro.pippo.core.PippoRuntimeException: Exception when reading the request body
	at ro.pippo.core.Request.getBody(Request.java:407)
	at com.mycompany.PippoApplication.lambda$onInit$7(PippoApplication.java:68)
	at ro.pippo.core.route.DefaultRouteContext.handleRoute(DefaultRouteContext.java:394)
	at ro.pippo.core.route.DefaultRouteContext.next(DefaultRouteContext.java:276)
	at ro.pippo.core.route.TrailingSlashHandler.handle(TrailingSlashHandler.java:67)
	at ro.pippo.core.route.DefaultRouteContext.handleRoute(DefaultRouteContext.java:394)
	at ro.pippo.core.route.DefaultRouteContext.next(DefaultRouteContext.java:276)
	at ro.pippo.core.route.RouteDispatcher.onRouteDispatch(RouteDispatcher.java:153)
	at ro.pippo.core.route.RouteDispatcher.dispatch(RouteDispatcher.java:101)
	at ro.pippo.core.PippoFilter.processRequest(PippoFilter.java:179)
	at ro.pippo.core.websocket.AbstractWebSocketFilter.processRequest(AbstractWebSocketFilter.java:37)
	at ro.pippo.core.PippoFilter.doFilter(PippoFilter.java:153)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at ro.pippo.jetty.JettyServer$PippoHandler.doHandle(JettyServer.java:257)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpChannelOverHttp.earlyEOF(HttpChannelOverHttp.java:239)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1444)
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:351)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:234)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1104)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1093)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.Reader.read(Reader.java:140)
	at ro.pippo.core.util.IoUtils.copy(IoUtils.java:69)
	at ro.pippo.core.util.IoUtils.copy(IoUtils.java:78)
	at ro.pippo.core.util.IoUtils.toString(IoUtils.java:60)
	at ro.pippo.core.Request.getBody(Request.java:405)
	... 41 more
```
 The error appears after I abort the request.

**Comment by munendrasn** [comment]
okay..how this should be handled??

**Comment by decebals** [comment]
What I don't understand is how it's possible to have a `Content_Length` header with an empty body, Who makes this request?

**Comment by munendrasn** [comment]
In other HTTP methods, i think nobody does..
In case of GET, what if `content-length` is set?? May not happen in case user facing application by it might happen if your calling pippo application from some other application and they set the header.
I feel that this should be handled at pippo end if possible otherwise application using pippo would affected

**Comment by munendrasn** [comment]
I had node.js application which receives some request from user(POST) and some processing and forwards it to pippo application as GET. In this all headers from original request were passed. During this i came across this issue..

**Comment by decebals** [comment]
I understand. Thanks for your explanation.

**Comment by decebals** [comment]
The HTTP 1.1 RFC specifies:

"When a Content-Length is given in a message where a message-body is allowed, its field value MUST exactly match the number of OCTETs in the message-body. HTTP/1.1 user agents MUST notify the user when an invalid length is received and detected."

See: http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4

**Comment by munendrasn** [comment]
okay..
thank you.. I think this answers the issue. Should I go ahead and close the issue??

**Comment by decebals** [comment]
They are many posts on the internet that say that are big problem when the content-length is not in sync with the size of body:
- https://stackoverflow.com/questions/5513230/http-connection-freezes-when-requests-content-length-exceeds-real-content-lengt
- https://github.com/hapijs/wreck/issues/178
- https://stackoverflow.com/questions/5513230/http-connection-freezes-when-requests-content-length-exceeds-real-content-lengt

I think that to eliminate this problems the sender of the request must verify the content length.

**Comment by decebals** [comment]
It's to late in Pippo to do this verification because I don't know the size of body.

**Comment by decebals** [comment]
I think that we can close this issue. What you say about this?
