### ISSUE TITLE
Error in Pippo-TJWS module

### ISSUE THREAD

**Issue by decebals** [decebals/pippo#381]
```
[INFO] --- exec-maven-plugin:1.5.0:exec (default-cli) @ pippo-helloworld ---
[main] ERROR ro.pippo.core.Languages - Please specify the supported languages in 'application.properties'. For example 'application.languages=en, ro, de, pt-BR' makes 'en' your default language.
[main] INFO ro.pippo.core.Languages - Using 'en' as default language.
[main] ERROR ro.pippo.core.Messages - Could not locate the default messages resource 'conf/messages.properties', please create it.
[main] INFO ro.pippo.tjws.TjwsServer - Starting RESTEasy TJWS Server 3.0.10.Final on port 8338
KEEPALIVE!: true
[main] INFO ro.pippo.core.PippoServlet - 
 ____  ____  ____  ____  _____
(  _ \(_  _)(  _ \(  _ \(  _  )
 ) __/ _)(_  ) __/ ) __/ )(_)(   http://pippo.ro
(__)  (____)(__)  (__)  (_____)  1.4.0

[main] ERROR ro.pippo.core.PippoServlet - Servlet init param 'applicationClassName' is missing
Exception in thread "main" ro.pippo.core.PippoRuntimeException: Cannot found application class name
    at ro.pippo.core.PippoServlet.createApplication(PippoServlet.java:153)
    at ro.pippo.core.PippoServlet.init(PippoServlet.java:81)
    at Acme.Serve.Serve.addServlet(Serve.java:514)
    at Acme.Serve.Serve.addServlet(Serve.java:498)
    at ro.pippo.tjws.TjwsServer.start(TjwsServer.java:94)
    at ro.pippo.core.Pippo.start(Pippo.java:156)
    at net.coatli.java.microservice.PippoHelloWorldApplication.main(PippoHelloWorldApplication.java:10)
[Thread-0] WARN ro.pippo.core.Pippo - Server is not started
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
    at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
    at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
    at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.862 s
[INFO] Finished at: 2017-07-26T22:42:32-05:00
[INFO] Final Memory: 20M/233M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (default-cli) on project pippo-helloworld: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

See https://groups.google.com/forum/#!topic/pippo-java/1iFLihPnJVM for more information.

**Comment by b0gg4rd** [comment]
Many thanks Decebals

**Comment by decebals** [comment]
@b0gg4rd You're welcome. I updated the SNAPSHOT version so you can use it.

**Comment by b0gg4rd** [comment]
@decebals excellent, again many thanks

**Comment by b0gg4rd** [comment]
Great. I use the 1.5.0-SNAPSHOT and it works.

[INFO] --- exec-maven-plugin:1.5.0:exec (default-cli) @ pippo-helloworld ---
19:29:50 [main] DEBUG ro.pippo.core.util.ClasspathUtils - Located 'conf/application.properties' in the context classpath
19:29:50 [main] DEBUG ro.pippo.core.PippoSettings - loading jar:file:/home/boggard/Development/java/workspace/micro-helloworld/pippo-helloworld/target/pippo-helloworld-0.1.0-SNAPSHOT.jar!/conf/application.properties
19:29:50 [main] INFO ro.pippo.core.Languages - Using 'en' as default language.
19:29:50 [main] DEBUG ro.pippo.core.util.ClasspathUtils - Located 'pippo/pippo-messages.properties' in the context classpath
19:29:50 [main] DEBUG ro.pippo.core.util.ClasspathUtils - Located 'pippo/pippo-messages_en.properties' in the context classpath
19:29:50 [main] DEBUG ro.pippo.core.util.ClasspathUtils - Located 'conf/messages.properties' in the context classpath
19:29:50 [main] DEBUG ro.pippo.core.util.ClasspathUtils - Located 'conf/messages_en.properties' in the context classpath
19:29:50 [main] DEBUG ro.pippo.core.util.ClasspathUtils - Located 'pippo/mime-types.properties' in the context classpath
19:29:51 [main] DEBUG ro.pippo.core.ContentTypeEngines - 'text/plain' content engine is 'ro.pippo.core.TextPlainEngine'
19:29:51 [main] DEBUG ro.pippo.core.Pippo - Application 'Pippo Hello World v0.1.0-SNAPSHOT'
19:29:51 [main] DEBUG ro.pippo.core.util.ServiceLocator - Locate service 'ro.pippo.core.WebServer' using ServiceLoader
19:29:51 [main] DEBUG ro.pippo.core.util.ServiceLocator - Found 'ro.pippo.tjws.TjwsServer'
19:29:51 [main] DEBUG ro.pippo.core.Pippo - Start server 'ro.pippo.tjws.TjwsServer@b81eda8'
19:29:51 [main] INFO ro.pippo.tjws.TjwsServer - Starting RESTEasy TJWS Server 3.1.4.Final on port 8338
19:29:51 [main] DEBUG ro.pippo.core.util.ClasspathUtils - Located 'pippo/pippo-builtin.properties' in the context classpath
19:29:51 [main] INFO ro.pippo.core.PippoServlet - 
 ____  ____  ____  ____  _____
(  _ \(_  _)(  _ \(  _ \(  _  )
 ) __/ _)(_  ) __/ ) __/ )(_)(   http://pippo.ro
(__)  (____)(__)  (__)  (_____)  1.5.0-SNAPSHOT

19:29:51 [main] DEBUG ro.pippo.core.PippoServlet - Serving application on context path '/'
19:29:51 [main] DEBUG ro.pippo.core.PippoServlet - Initializing Route Dispatcher
19:29:51 [main] DEBUG ro.pippo.core.route.RouteDispatcher - Initializing application 'Pippo Hello World v0.1.0-SNAPSHOT'
19:29:51 [main] DEBUG ro.pippo.core.util.ServiceLocator - Locate service 'ro.pippo.core.Initializer' using ServiceLoader
19:29:51 [main] DEBUG ro.pippo.core.util.ServiceLocator - Locate service 'ro.pippo.core.route.RouteTransformer' using ServiceLoader
19:29:51 [main] DEBUG ro.pippo.core.route.DefaultRouter - Add route for GET '/'
19:29:51 [main] DEBUG ro.pippo.core.route.DefaultRouter - Compile routes
19:29:51 [main] DEBUG ro.pippo.core.util.ServiceLocator - Locate service 'ro.pippo.core.route.RouteContextFactory' using ServiceLoader
19:29:51 [main] DEBUG ro.pippo.core.route.RouteDispatcher - RouteContext factory is 'ro.pippo.core.route.DefaultRouteContextFactory'
19:29:51 [main] INFO ro.pippo.core.PippoServlet - Pippo started (PROD)
